version: '3.8'
services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/project
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000
